// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkVSMalm7WDDd8BleyEzCW5EOP17WvOjE',
    appId: '1:353497367063:web:993c9c66a2dc4878cfd252',
    messagingSenderId: '353497367063',
    projectId: 'shaz-chat-app',
    authDomain: 'shaz-chat-app.firebaseapp.com',
    storageBucket: 'shaz-chat-app.firebasestorage.app',
    measurementId: 'G-RRF5NRFSDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCav9DFcYgeCs0L8RpPRbmGbUY01fFFEP8',
    appId: '1:353497367063:android:4117d3483c69bc60cfd252',
    messagingSenderId: '353497367063',
    projectId: 'shaz-chat-app',
    storageBucket: 'shaz-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuIU-keoDaVRdp2fwTCARYTWKov68AW6E',
    appId: '1:353497367063:ios:fcf643f00164694acfd252',
    messagingSenderId: '353497367063',
    projectId: 'shaz-chat-app',
    storageBucket: 'shaz-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuIU-keoDaVRdp2fwTCARYTWKov68AW6E',
    appId: '1:353497367063:ios:fcf643f00164694acfd252',
    messagingSenderId: '353497367063',
    projectId: 'shaz-chat-app',
    storageBucket: 'shaz-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkVSMalm7WDDd8BleyEzCW5EOP17WvOjE',
    appId: '1:353497367063:web:8c288e361d6fb0edcfd252',
    messagingSenderId: '353497367063',
    projectId: 'shaz-chat-app',
    authDomain: 'shaz-chat-app.firebaseapp.com',
    storageBucket: 'shaz-chat-app.firebasestorage.app',
    measurementId: 'G-BS6XF8HBM0',
  );
}
